# 1.3.1
Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и
единицами.


In [7]:
import numpy as np
A = [[(j + i + 1) % 2 for j in range(8)] for i in range(8)]
for i in A:
    print(i)

[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]
[1, 0, 1, 0, 1, 0, 1, 0]
[0, 1, 0, 1, 0, 1, 0, 1]


------------------------------------------------------------

# 1.3.2
Создать 5x5 матрицу со значениями в строках от 0 до 4. Для создания
необходимо использовать функцию arrange

In [26]:


x = np.matrix([np.arange(0, 5)]*5)
print(x)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


# 1.3.3
Создать массив 3x3x3 со случайными значениями

In [67]:
import numpy as np
print(np.array([np.random.random(3) for i in range(3)]))

[[0.7752083  0.7575345  0.86219944]
 [0.91539841 0.6513093  0.89986385]
 [0.86918941 0.28735192 0.50066693]]


# 1.3.4
Создать матрицу с 0 внутри, и 1 на границах.


In [ ]:
import numpy as np
n = 5 
a = np.ones((n,n), dtype=int)
a[1:-1,1:-1] = 0 
print(a)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# 1.3.5
Создайте массив и отсортируйте его по убыванию.



In [80]:
from numpy import array, sort
a = array([4, 8, 1, 6, 3, 9])
a_desc = sort(a)[::-1]  
print(a_desc)

[9 8 6 4 3 1]


# 1.3.6
Создайте матрицу, выведите ее форму, размер и размерность.

In [81]:
from numpy import array

A = array([[1, 2, 3, 4],
           [5, 6, 7, 8],
           [9, 10, 11, 12]])

print("Матрица A:")
print(A)
print("Форма (shape):", A.shape)      # (3, 4)
print("Размер (size):", A.size)       # 12
print("Размерность (ndim):", A.ndim)  # 2

Матрица A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Форма (shape): (3, 4)
Размер (size): 12
Размерность (ndim): 2


------------------------------------------------------------

# 2.3.1
Найдитe евклидово расстояние между двумя Series (точками) a и b, не
используя встроенную формулу.


In [85]:
from numpy import array, sqrt
a = array([1, 4, 7, 2])
b = array([3, 0, 5, 8])
print("Евклидово расстояние:", sqrt(sum((pow(a-b,2)))))

Евклидово расстояние: 7.745966692414834


# 2.3.2
Найдите в Интернете ссылку на любой csv файл и сформируйте из него
фрейм данных (например, коллекцию фреймов данных можно найти
здесь: https://github.com/akmand/datasets).

In [ ]:
import pandas as pd

url = "https://raw.githubusercontent.com/akmand/datasets/main/heart.csv"
dataframe = pd.read_csv(url)

# 2.3.3
Продеать с csv фреймом то же саое что и в 2.2.[5-7]


### 2.2.5
```py
dataframe.head(2)
dataframe.tail(3)
dataframe.shape
dataframe.describe()
```
### 2.2.6
```py
dataframe.iloc[1:4]
```
### 2.2.7 
```py
dataframe[dataframe['PClass'] == '1st'].head(2)
'''

In [94]:
import pandas as pd

url = "https://raw.githubusercontent.com/akmand/datasets/main/heart.csv"
df = pd.read_csv(url)

# 2.2.5
print("=== 2.2.5 ===")
print(df.head(2))
print("\n")
print(df.tail(3))
print("\n")
print("Форма:", df.shape)
print("\n")
print(df.describe())
print("\n")
# 2.2.6
print("=== 2.2.6 ===")
print(df.iloc[1:4])
print("\n")
# 2.2.7
print("=== 2.2.7 ===")
print(df['2'])

=== 2.2.5 ===
    1   2   3   4   5   6   7   8   9  10  ...  36  37  38  39  40  41  42  \
0  59  52  70  67  73  66  72  61  58  52  ...  56  62  56  72  62  74  74   
1  72  62  69  67  78  82  74  65  69  63  ...  71  63  60  69  73  67  71   

   43  44  45  
0  64  67   1  
1  56  58   1  

[2 rows x 45 columns]


      1   2   3   4   5   6   7   8   9  10  ...  36  37  38  39  40  41  42  \
264  75  73  72  77  68  67  76  73  67  65  ...  67  72  71  79  75  77  75   
265  59  62  72  74  66  66  74  76  63  67  ...  71  67  69  77  78  77  76   
266  64  66  68  71  62  64  74  73  63  67  ...  69  68  65  75  72  62  64   

     43  44  45  
264  67  71   0  
265  70  70   0  
266  57  54   0  

[3 rows x 45 columns]


Форма: (267, 45)


                1           2           3           4           5           6  \
count  267.000000  267.000000  267.000000  267.000000  267.000000  267.000000   
mean    66.183521   64.913858   68.677903   69.078652   64.801498   63.966292  

------------------------------------------------------------

# 3.3.2
Загрузить фрейм данных по ссылке:
https://raw.githubusercontent.com/akmand/datasets/master/iris.csv.
Необходимо выполнить нормализацию первого числового признака
(sepal_length_cm) с использованием минимаксного преобразования, а
второго (sepal_width_cm) с задействованием z-масштабирования.

In [97]:
import pandas as pd
from numpy import min, max, mean, std

# Загрузка данных
url = "https://raw.githubusercontent.com/akmand/datasets/master/iris.csv"
df = pd.read_csv(url)

# Извлекаем нужные признаки как массивы NumPy
sepal_length = df['sepal_length_cm'].values
sepal_width = df['sepal_width_cm'].values

# Минимаксная нормализация для sepal_length: (x - min) / (max - min)
sepal_length_norm = (sepal_length - min(sepal_length)) / (max(sepal_length) - min(sepal_length))

# Z-масштабирование для sepal_width: (x - mean) / std
sepal_width_scaled = (sepal_width - mean(sepal_width)) / std(sepal_width)

# Выводим первые 5 значений для проверки
print("Нормализованный sepal_length (минимакс):")
print(sepal_length_norm )

print("\nМасштабированный sepal_width (z-score):")
print(sepal_width_scaled)

Нормализованный sepal_length (минимакс):
[0.22222222 0.16666667 0.11111111 0.08333333 0.19444444 0.30555556
 0.08333333 0.19444444 0.02777778 0.16666667 0.30555556 0.13888889
 0.13888889 0.         0.41666667 0.38888889 0.30555556 0.22222222
 0.38888889 0.22222222 0.30555556 0.22222222 0.08333333 0.22222222
 0.13888889 0.19444444 0.19444444 0.25       0.25       0.11111111
 0.13888889 0.30555556 0.25       0.33333333 0.16666667 0.19444444
 0.33333333 0.16666667 0.02777778 0.22222222 0.19444444 0.05555556
 0.02777778 0.19444444 0.22222222 0.13888889 0.22222222 0.08333333
 0.27777778 0.19444444 0.75       0.58333333 0.72222222 0.33333333
 0.61111111 0.38888889 0.55555556 0.16666667 0.63888889 0.25
 0.19444444 0.44444444 0.47222222 0.5        0.36111111 0.66666667
 0.36111111 0.41666667 0.52777778 0.36111111 0.44444444 0.5
 0.55555556 0.5        0.58333333 0.63888889 0.69444444 0.66666667
 0.47222222 0.38888889 0.33333333 0.33333333 0.41666667 0.47222222
 0.30555556 0.47222222 0.66666667 